



# druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://10.32.71.163:3306/mybatis-example
      username: root
      password: Sjzxz@cxdbdb82077274
      driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis 彻底跑起了mybatis-config.xml
# mapperxml文件的配置 settings的配置 别名的配置
#mybatis:
#  mapper-locations: classpath:/mappers/*.xml #指定xml文件的配置
#  type-aliases-package: org.example.pojo
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl